FROM ruby:latest

RUN mkdir -p /usr/src/pathfinding
WORKDIR /usr/src/pathfinding

ADD ./Gemfile /usr/src/pathfinding/Gemfile
ADD ./Gemfile.lock /usr/src/pathfinding/Gemfile.lock

RUN bundle
ADD spec/ /usr/src/pathfinding/spec

