FROM node:latest

RUN mkdir -p /usr/src/pathfinding
WORKDIR /usr/src/pathfinding

ADD ./package.json /usr/src/pathfinding/package.json

RUN npm install

RUN mkdir /usr/src/pathfinding/spec
ADD spec.js /usr/src/pathfinding/spec/
ADD mocha.opts /usr/src/pathfinding/
